# Generated by Django 4.1 on 2022-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erjaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asli', models.CharField(max_length=10, null=True)),
                ('faree', models.CharField(max_length=10, null=True)),
                ('bakhsh', models.CharField(choices=[('01', '01'), ('02', '02'), ('07', '07')], default='02', max_length=3)),
                ('babat', models.CharField(choices=[('بازدید', 'بازدید'), ('تفکیک', 'تفکیک')], default='بازدید', max_length=250)),
            ],
        ),
    ]
