# Generated by Django 4.1 on 2022-02-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erjaat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erjaat',
            name='malek_mellicode',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
